name: Deploy to Amazon ECS

on: 
  push: 
    branches: [ "main" ]
    paths:
      - task-definition.json
 
env:
  AWS_REGION: ap-northeast-1
  ECS_TASK_DEFINITION: task-definition.json
  ECS_SERVICE: one-ecs-service
  ECS_CLUSTER: one-ecs-cluster

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role-poker_app_deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: false
