name: ECR Push Triggered Action

on:
  repository_dispatch:
    types: ECR Push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Image tag is ${{ github.event.client_payload.image_tag }}"
